apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-ui
spec:
  rules:
  - host: hubble.k8s.tosuke.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hubble-ui
            port: 
              number: 80
