apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hubble-ui
spec:
  virtualhost:
    fqdn: hubble.k8s.tosuke.me
    tls:
      secretName: hubble-k8s-tosuke-me-cert
      minimumProtocolVersion: "1.3"
  # FIXME: Contour doesn't support gRPC-Web only endpoints 
  # https://github.com/projectcontour/contour/issues/4290
  tcpproxy:
    services:
    - name: hubble-ui
      port: 80
  routes:
  - conditions:
    - prefix: /
    services: # provide dummy services for redirect to https
    - name: hubble-ui
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ui
spec:
  dnsNames:
  - hubble.k8s.tosuke.me
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  secretName: hubble-k8s-tosuke-me-cert
