apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ui
  labels:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble-ui
spec:
  routes:
  - match: Host(`hubble.k8s.tosuke.me`)
    kind: Rule
    services:
    - name: hubble-ui
      port: 80
  tls:
    secretName: hubble-k8s-tosuke-me-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ui
  labels:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble-ui
spec:
  dnsNames:
  - hubble.k8s.tosuke.me
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
  secretName: hubble-k8s-tosuke-me-cert

