apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- hubble-ui-ingress.yaml
- hubble-ui-authz-listener.yaml

helmCharts:
- name: cilium
  repo: https://helm.cilium.io
  version: "1.13.0-rc1"
  namespace: kube-system
  valuesFile: values.yaml

patches:
- target:
    kind: Service
    name: cilium-ingress
  patch: |-
    - op: add
      path: /spec/ipFamilyPolicy
      value: PreferDualStack
- target:
    kind: IngressClass
    name: cilium
  patch: |-
    - op: add
      path: /metadata/annotations/ingressclass.kubernetes.io~1is-default-class
      value: "true"