apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bird
spec:
  selector:
    matchLabels:
      app: bird
  template:
    metadata:
      labels:
        app: bird
    spec:
      containers:
      - name: bird
        env:
        - name: BIRD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: BIRD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: BIRD_ML_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "ghcr.io/tosuke-lab/bird-container:2.0.9"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 500m
            memory: 250Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
        volumeMounts:
        - name: bird-cm
          mountPath: /usr/local/etc
      volumes:
      - name: bird-cm
        configMap:
          name: bird-cm
      hostNetwork: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
