apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: purelb

resources:
- namespace.yaml

helmCharts:
- name: purelb
  repo: https://gitlab.com/api/v4/projects/20400619/packages/helm/stable
  version: 0.6.4
  namespace: purelb
  includeCRDs: true
  valuesInline:
    lbnodeagent:
      tolerations:
      - operator: Exists
        key: "node-role.kubernetes.io/master"
