apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: originissuer-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["cert-manager.k8s.cloudflare.com"]
  resources: ["originissuers"]
  verbs: ["get","watch","list"]