apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
- namespace.yaml
- rbac.yaml

helmCharts:
- name: traefik
  repo: https://helm.traefik.io/traefik
  version: "17.0.5"
  includeCRDs: true
  releaseName: homelab
  namespace: traefik
  valuesFile: values.yaml
