experimental:
  http3:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: true

deployment:
  kind: DaemonSet

service:
  annotations:
    "purelb.io/allow-shared-ip": public-traefik
  ipFamilyPolicy: PreferDualStack

ports:
  web:
    redirectTo: websecure
  websecure:
    http3: true

tlsOptions:
  default:
    sniStrict: true
    minVersion: VersionTLS12
    cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    curvePreferences:
    - CurveP384
    - CurveP521

logs:
  access:
    enabled: true