experimental:
  http3:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: true

deployment:
  kind: DaemonSet

service:
  annotations:
    purelb.io/allow-shared-ip: public
    external-dns.alpha.kubernetes.io/hostname: traefik.dns.tosuke.me
    external-dns.alpha.kubernetes.io/ttl: "180"
  ipFamilyPolicy: PreferDualStack

ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8080
    expose: true
    exposedPort: 80
    protocol: TCP
    redirectTo: websecure
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
      options: ""
      certResolver: ""
      domains: []
    http3: true
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100
    protocol: TCP

tlsOptions:
  default:
    sniStrict: true
    minVersion: VersionTLS12
    cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    curvePreferences:
    - CurveP384
    - CurveP521

logs:
  access:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: false
    allowEmptyServices: false
    namespaces: []
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true
