apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dex
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`id.tosuke.me`)
    kind: Rule
    services:
    - kind: TraefikService
      namespace: oidc
      name: dex
  tls:
    secretName: cloudflare-origin-cert-wildcard-tosuke-me
    options:
      name: cloudflare-origin
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dex
spec:
  endpoints:
  - dnsName: id.tosuke.me
    recordType: CNAME
    targets: [traefik.dns.tosuke.me]
    providerSpecific:
    - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
      value: "true"