apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: external-kube-apiserver
spec:
  entryPoints: [websecure]
  routes:
  - match: "Host(`k8s.tosuke.me`) && Method(`GET`) && Path(`/.well-known/openid-configuration`, `/openid/v1/jwks`)"
    kind: Rule
    services:
    - kind: TraefikService
      namespace: default
      name: external-kube-apiserver
    
  - match: Host(`k8s.tosuke.me`)
    kind: Rule
    services:
    - kind: TraefikService
      namespace: default
      name: external-kube-apiserver
  tls:
    secretName: cloudflare-origin-cert-wildcard-tosuke-me
    domains:
    - main: k8s.tosuke.me
    options:
      name: cloudflare-origin
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kube-apiserver
spec:
  endpoints:
  - dnsName: k8s.tosuke.me
    recordType: CNAME
    targets: [traefik.dns.tosuke.me]
    providerSpecific:
    - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
      value: "true"