apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateways

resources:
- namespace.yaml
- issuers/cloudflare-origin-issuer.yaml
- issuers/letsencrypt-issuer.yaml
- cloudflare-origin-tls.yaml
- certificates.yaml
- edgerouter-dashboard-gateway.yaml
- dex-gateway.yaml
- hubble-ui-gateway.yaml
- kube-apiserver.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: cloudflare-origin-pull-ca
  files:
  - ca.crt=cloudflare-origin-pull-ca.pem
