apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: dex

resources:
- rbac.yaml
- deployment.yaml
- secret.yaml
- ingress.yaml

images:
- name: ghcr.io/dexidp/dex
  newTag: v2.30.0

configMapGenerator:
- name: dex-config
  files:
  - config.yaml