apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oidc-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: github-oidc-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: github-oidc-credentials