apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
- namespace.yaml
- gcpsm-cluster-secret-store.yaml
- webhook-ca.yaml

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.6.1
  releaseName: homelab
  namespace: external-secrets
  includeCRDs: true
  valuesInline:
    certController:
      create: false
    webhook:
      tolerations:
      - operator: Exists
        key: "node-role.kubernetes.io/master"
    tolerations:
    - operator: Exists
      key: "node-role.kubernetes.io/master"

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/cert-manager.io~1inject-ca-from
      value: external-secrets/external-secrets-webhook-ca
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
  patch: |-
    - op: add
      path: /metadata/annotations/cert-manager.io~1inject-ca-from
      value: external-secrets/external-secrets-webhook-ca