apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kube-apiserver
spec:
  entryPoints:
  - kubernetes
  routes:
  - match: HostSNI(`k8s.tosuke.me`)
    services:
    - name: kubernetes
      port: 443
  tls:
    passthrough: true
--- 
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kube-apiserver
spec:
  endpoints:
  - dnsName: k8s.tosuke.me
    recordType: CNAME
    targets: [traefik.dns.tosuke.me]