apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "oidc:tosuke-homelab:admin"