apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-view
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-cluster-view: "true"
---
# cluster-view can view cluster scope resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-view-cluster-scope
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-view: "true"
rules:
- apiGroups: [""]
  resources: ["nodes", "componentstatuses", "persistentvolumes"]
  verbs: ["get","watch","list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","watch","list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get","watch","list"]
