# All unauthenticated & authenticated users can discover OIDC issuer

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-discovery
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: system:anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery