apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-client-secret-hubble-ui
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: dex-client-secret-hubble-ui
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      key: dex-client-secret-hubble-ui
