apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

commonLabels:
  app.kubernetes.io/name: external-dns

resources:
- namespace.yaml
- https://kubernetes-sigs.github.io/external-dns/v0.13.1/contributing/crd-source/crd-manifest.yaml
- rbac.yaml
- secret.yaml
- deployment.yaml