apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: cloudflare-dns
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare-dns-api-token