apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: cloudflare-dns-api
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-dns-api-token