apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- namespace.yaml
- origin-ca-issuer

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  namespace: cert-manager
  releaseName: homelab
  includeCRDs: true
  valuesInline:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
